# Cleaning of consolidated consumption dataset

In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

pd.set_option("display.max_columns", None)

In [2]:
df_consumption = pd.read_csv("../../dataset/clean/training/production/tabular/consumption_consolidated.csv")
df_consumption.head()

,Control Number,District,Street,Connection Type,Connection Status,2019_DEC,2020_JAN,2020_FEB,2020_MAR,2020_APR,2020_MAY,2020_JUN,2020_JUL,2020_AUG,2020_SEP,2020_OCT,2020_NOV,2020_DEC,2022_JAN,2022_FEB,2022_MAR,2022_APR,2022_MAY,2022_JUN,2022_JUL,2022_AUG,2022_SEP,2022_OCT,2022_NOV,2022_DEC,2023_JAN,2023_FEB,2023_MAR,2023_APR,2023_MAY,2023_JUN,2023_JUL,2023_AUG,2023_SEP,2023_OCT,2023_NOV,2023_DEC,2024_JAN,2024_FEB,2024_MAR,2024_APR,2024_MAY,2024_JUN,2024_JUL,2024_AUG,2024_SEP,2024_OCT,2024_NOV,2024_DEC,2025_JAN,2025_FEB,2025_MAR,2025_APR,2025_MAY
0,0.0,NaN,NaN,NaN,Unknown,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,107.0,48.0,NaN,NaN,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,121.0,District 2,Esparrago Street,Residential,Disconnected,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
2,50964.0,NaN,NaN,NaN,Unknown,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,17.0,12.0,12.0,6.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,500001.0,District 4,Esparrago Street,Residential,Disconnected,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
4,500002.0,District 4,Esparrago Street,Residential,Active,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,13.0,5.0,18.0,10.0,0.0,35.0,0.0,33.0,33.0,19.0,16.0,13.0,21.0,10.0,0.0,15.0,7.0,22.0,68.0,53.0,13.0,20.0,30.0,30.0,18.0,9.0,0.0,7.0,18.0,18.0,0.0,0.0,0.0,0.0,20.0,0.0,0.0,0.0,0.0,0.0,153.0

### Checking for null values in each column

In [3]:
df_consumption.isnull().sum()

Control Number         0
District             300
Street                13
Connection Type       13
Connection Status      0
2019_DEC             622
2020_JAN             617
2020_FEB             574
2020_MAR             561
2020_APR             561
2020_MAY             559
2020_JUN             561
2020_JUL             559
2020_AUG             553
2020_SEP             486
2020_OCT             485
2020_NOV             485
2020_DEC             622
2022_JAN             319
2022_FEB             303
2022_MAR             299
2022_APR             280
2022_MAY             279
2022_JUN             253
2022_JUL             253
2022_AUG             301
2022_SEP             301
2022_OCT             205
2022_NOV             179
2022_DEC             171
2023_JAN             171
2023_FEB             167
2023_MAR             172
2023_APR             166
2023_MAY             165
2023_JUN             161
2023_JUL             157
2023_AUG             139
2023_SEP             126
2023_OCT             113
2023_NOV             150
2023_DEC             150
2024_JAN              73
2024_FEB              75
2024_MAR              75
2024_APR              59
2024_MAY              56
2024_JUN              56
2024_JUL              61
2024_AUG              48
2024_SEP              45
2024_OCT              38
2024_NOV              34
2024_DEC              34
2025_JAN              24
2025_FEB              21
2025_MAR              19
2025_APR              17
2025_MAY              13
dtype: int64

### Checking Control Number duplicates

In [4]:
# Check for duplicates
df_consumption.duplicated(subset=["Control Number"]).sum()

# Display duplicate rows
df_consumption[df_consumption.duplicated(subset=["Control Number"], keep=False)]

,Control Number,District,Street,Connection Type,Connection Status,2019_DEC,2020_JAN,2020_FEB,2020_MAR,2020_APR,2020_MAY,2020_JUN,2020_JUL,2020_AUG,2020_SEP,2020_OCT,2020_NOV,2020_DEC,2022_JAN,2022_FEB,2022_MAR,2022_APR,2022_MAY,2022_JUN,2022_JUL,2022_AUG,2022_SEP,2022_OCT,2022_NOV,2022_DEC,2023_JAN,2023_FEB,2023_MAR,2023_APR,2023_MAY,2023_JUN,2023_JUL,2023_AUG,2023_SEP,2023_OCT,2023_NOV,2023_DEC,2024_JAN,2024_FEB,2024_MAR,2024_APR,2024_MAY,2024_JUN,2024_JUL,2024_AUG,2024_SEP,2024_OCT,2024_NOV,2024_DEC,2025_JAN,2025_FEB,2025_MAR,2025_APR,2025_MAY
746,500744.0,District 2,Jones Street,Residential,Active,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,3.0,0.5,0.0,0.5,0.0,0.0,0.0,0.5,0.0
747,500744.0,District 2,Jones Street,Residential,Disconnected,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,3.0,0.5,0.0,0.5,0.0,0.0,0.0,0.5,0.0
966,500963.0,District 2,Jones Street,Residential,Active,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,4.0,4.0,4.5,3.0,0.0,6.5,0.0,8.5,8.5,4.0,4.0,5.0,8.0,4.0,0.0,3.5,4.5,3.5,11.5,21.0,9.0,12.5,10.5,10.0,6.5,8.5,7.5,10.0,6.5,8.0,2.0,4.5,2.0,0.0,0.0,0.0,0.0,0.0,0.5,0.0,0.0
967,500963.0,District 2,Jones Street,Residential,Disconnected,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,4.0,4.0,4.5,3.0,0.0,6.5,0.0,8.5,8.5,4.0,4.0,5.0,8.0,4.0,0.0,3.5,4.5,3.5,11.5,21.0,9.0,12.5,10.5,10.0,6.5,8.5,7.5,10.0,6.5,8.0,2.0,4.5,2.0,0.0,0.0,0.0,0.0,0.0,0.5,0.0,0.0
1103,501099.0,District 2,Balcavem Street,Residential,Active,7.5,5.0,5.0,6.5,3.5,7.5,6.0,3.5,0.0,0.0,0.0,0.0,7.5,12.0,10.0,12.5,8.5,0.0,18.5,9.5,19.5,19.0,10.0,13.0,11.0,7.0,9.5,0.0,10.0,13.5,13.0,13.0,23.5,9.5,14.5,15.5,15.5,6.5,10.5,4.0,3.0,1.0,1.0,1.5,2.0,2.5,2.0,1.5,2.0,1.5,1.5,2.5,2.5,2.5
1104,501099.0,District 2,Balcavem Street,Residential,Disconnected,7.5,5.0,5.0,6.5,3.5,7.5,6.0,3.5,0.0,0.0,0.0,0.0,7.5,12.0,10.0,12.5,8.5,0.0,18.5,9.5,19.5,19.0,10.0,13.0,11.0,7.0,9.5,0.0,10.0,13.5,13.0,13.0,23.5,9.5,14.5,15.5,15.5,6.5,10.5,4.0,3.0,1.0,1.0,1.5,2.0,2.5,2.0,1.5,2.0,1.5,1.5,2.5,2.5,2.5
1921,501916.0,District 2,Jones Street,Commercial,Active,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,8.0,13.0,30.0,3.5,12.5,14.5,11.5,12.0,11.0,13.5,22.0,33.5,26.5,30.0,35.0,26.5,23.0
1922,501916.0,District 2,Jones Street,Commercial,Disconnected,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,8.0,13.0,30.0,3.5,12.5,14.5,11.5,12.0,11.0,13.5,22.0,33.5,26.5,30.0,35.0,26.5,23.0
2005,502001.0,District 4,Villamor Street,Residential,Active,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,0.0,0.0,20.0,0.0,94.0,10.0,10.0,4.0,0.0,0.0,0.0,373.0,372.0,4.0,12.0,10.0,10.0,0.0,0.0,0.0,0.0,25.5,25.0,214.5,18.0,15.0,15.0,25.0,22.5,22.5
2006,502001.0,District 4,Villamor Street,Residential,Active,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,0.0,0.0,20.0,0.0,94.0,10.0,10.0,4.0,0.0,0.0,0.0,373.0,372.0,4.0,12.0,10.0,10.0,0.0,0.0,0.0,0.0,25.5,25.0,214.5,18.0,15.0,15.0,25.0,22.5,22.5

In [6]:
# Keep first instance of duplicate rows
df_consumption = df_consumption.drop_duplicates(subset=["Control Number"], keep="first")

# Overwrite source dataset 
df_consumption.to_csv("../../dataset/clean/training/production/tabular/consumption_consolidated.csv", index=False)

In [7]:
# Recheck for duplicate control numbers
df_consumption.duplicated(subset=["Control Number"]).sum()

np.int64(0)

### Checking missing districts

In [9]:
# Display records with missing district but non-missing street
df_missing_dist_only = df_consumption[df_consumption["District"].isnull() & df_consumption["Street"].notnull()]
df_missing_dist_only.head()

,Control Number,District,Street,Connection Type,Connection Status,2019_DEC,2020_JAN,2020_FEB,2020_MAR,2020_APR,2020_MAY,2020_JUN,2020_JUL,2020_AUG,2020_SEP,2020_OCT,2020_NOV,2020_DEC,2022_JAN,2022_FEB,2022_MAR,2022_APR,2022_MAY,2022_JUN,2022_JUL,2022_AUG,2022_SEP,2022_OCT,2022_NOV,2022_DEC,2023_JAN,2023_FEB,2023_MAR,2023_APR,2023_MAY,2023_JUN,2023_JUL,2023_AUG,2023_SEP,2023_OCT,2023_NOV,2023_DEC,2024_JAN,2024_FEB,2024_MAR,2024_APR,2024_MAY,2024_JUN,2024_JUL,2024_AUG,2024_SEP,2024_OCT,2024_NOV,2024_DEC,2025_JAN,2025_FEB,2025_MAR,2025_APR,2025_MAY
18,500016.0,NaN,Moyot Street,Residential,Active,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,4.0,0.0,0.0,0.0,0.0,20.0,27.0,15.0,22.0,0.0,26.0,0.0,34.0,33.0,17.0,14.0,7.0,16.0,31.0,0.0,21.0,23.0,28.0,26.0,39.0,20.0,23.0,58.0,58.0,0.0,16.0,27.0,22.0,25.0,19.0,21.0,18.0,16.0,17.0,13.0,11.0,12.0,11.0,18.0,19.0,0.0
19,500017.0,NaN,Moyot Street,Residential,Disconnected,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
20,500018.0,NaN,Moyot Street,Residential,Active,14.0,12.0,0.0,92.0,46.0,26.0,16.0,15.0,18.0,10.0,20.0,20.0,14.0,22.0,13.0,24.0,11.0,0.0,31.0,0.0,0.0,0.0,0.0,0.0,240.0,34.0,34.0,0.0,43.0,44.0,54.0,36.0,93.0,37.0,43.0,50.0,50.0,30.0,20.0,15.0,35.0,45.0,21.0,45.0,52.0,50.0,43.0,47.0,58.0,137.0,98.0,15.0,12.0,0.0
39,500037.0,NaN,Moyot Street,Residential,Disconnected,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
40,500038.0,NaN,Moyot Street,Residential,Active,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,34.0,26.0,37.0,39.0,0.0,33.0,36.0,28.0,40.0,0.0,16.0,0.0,83.0,83.0,28.0,0.0,0.0,20.0,13.0,0.0,28.0,34.0,43.0,25.0,67.0,25.0,34.0,34.0,33.0,25.0,27.0,36.0,43.0,20.0,38.0,1.0,28.0,28.0,32.0,16.0,34.0,34.0,27.0,35.0,30.0,32.0

In [10]:
# Display records with missing district and street
df_missing_both = df_consumption[df_consumption["District"].isnull() & df_consumption["Street"].isnull()]
df_missing_both.head()

,Control Number,District,Street,Connection Type,Connection Status,2019_DEC,2020_JAN,2020_FEB,2020_MAR,2020_APR,2020_MAY,2020_JUN,2020_JUL,2020_AUG,2020_SEP,2020_OCT,2020_NOV,2020_DEC,2022_JAN,2022_FEB,2022_MAR,2022_APR,2022_MAY,2022_JUN,2022_JUL,2022_AUG,2022_SEP,2022_OCT,2022_NOV,2022_DEC,2023_JAN,2023_FEB,2023_MAR,2023_APR,2023_MAY,2023_JUN,2023_JUL,2023_AUG,2023_SEP,2023_OCT,2023_NOV,2023_DEC,2024_JAN,2024_FEB,2024_MAR,2024_APR,2024_MAY,2024_JUN,2024_JUL,2024_AUG,2024_SEP,2024_OCT,2024_NOV,2024_DEC,2025_JAN,2025_FEB,2025_MAR,2025_APR,2025_MAY
0,0.0,NaN,NaN,NaN,Unknown,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,107.0,48.0,NaN,NaN,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,50964.0,NaN,NaN,NaN,Unknown,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,17.0,12.0,12.0,6.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1114,501109.0,NaN,NaN,NaN,Unknown,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1364,501359.0,NaN,NaN,NaN,Unknown,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,30.0,15.0,12.0,9.0,0.0,67.0,0.0,0.0,22.0,31.0,72.0,0.0,149.0,149.0,77.0,56.0,58.0,75.0,54.0,0.0,41.0,19.0,20.0,148.0,216.0,7.0,13.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1386,501381.0,NaN,NaN,NaN,Unknown,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [12]:
# Save DFs to csv to misc folder
df_missing_dist_only.to_csv("../../dataset/clean/training/production/misc/missing_district_only.csv", index=False)
df_missing_both.to_csv("../../dataset/clean/training/production/misc/missing_district_street.csv", index=False)

### Checking missing connection type

In [13]:
df_missing_conn_type = df_consumption[df_consumption["Connection Type"].isnull()]
df_missing_conn_type.to_csv("../../dataset/clean/training/production/misc/missing_connection_type.csv", index=False)

In [14]:
df_missing_conn_type.head()

,Control Number,District,Street,Connection Type,Connection Status,2019_DEC,2020_JAN,2020_FEB,2020_MAR,2020_APR,2020_MAY,2020_JUN,2020_JUL,2020_AUG,2020_SEP,2020_OCT,2020_NOV,2020_DEC,2022_JAN,2022_FEB,2022_MAR,2022_APR,2022_MAY,2022_JUN,2022_JUL,2022_AUG,2022_SEP,2022_OCT,2022_NOV,2022_DEC,2023_JAN,2023_FEB,2023_MAR,2023_APR,2023_MAY,2023_JUN,2023_JUL,2023_AUG,2023_SEP,2023_OCT,2023_NOV,2023_DEC,2024_JAN,2024_FEB,2024_MAR,2024_APR,2024_MAY,2024_JUN,2024_JUL,2024_AUG,2024_SEP,2024_OCT,2024_NOV,2024_DEC,2025_JAN,2025_FEB,2025_MAR,2025_APR,2025_MAY
0,0.0,NaN,NaN,NaN,Unknown,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,107.0,48.0,NaN,NaN,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,50964.0,NaN,NaN,NaN,Unknown,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,17.0,12.0,12.0,6.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1114,501109.0,NaN,NaN,NaN,Unknown,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1364,501359.0,NaN,NaN,NaN,Unknown,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,30.0,15.0,12.0,9.0,0.0,67.0,0.0,0.0,22.0,31.0,72.0,0.0,149.0,149.0,77.0,56.0,58.0,75.0,54.0,0.0,41.0,19.0,20.0,148.0,216.0,7.0,13.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1386,501381.0,NaN,NaN,NaN,Unknown,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

### Dropping insignificant rows

We drop the insignificant rows, which are determined so because they are either irrecoverable or inconsequential.

In [15]:
year_month_cols = df_consumption.columns[5:]
year_month_cols

Index(['2019_DEC', '2020_JAN', '2020_FEB', '2020_MAR', '2020_APR', '2020_MAY',
       '2020_JUN', '2020_JUL', '2020_AUG', '2020_SEP', '2020_OCT', '2020_NOV',
       '2020_DEC', '2022_JAN', '2022_FEB', '2022_MAR', '2022_APR', '2022_MAY',
       '2022_JUN', '2022_JUL', '2022_AUG', '2022_SEP', '2022_OCT', '2022_NOV',
       '2022_DEC', '2023_JAN', '2023_FEB', '2023_MAR', '2023_APR', '2023_MAY',
       '2023_JUN', '2023_JUL', '2023_AUG', '2023_SEP', '2023_OCT', '2023_NOV',
       '2023_DEC', '2024_JAN', '2024_FEB', '2024_MAR', '2024_APR', '2024_MAY',
       '2024_JUN', '2024_JUL', '2024_AUG', '2024_SEP', '2024_OCT', '2024_NOV',
       '2024_DEC', '2025_JAN', '2025_FEB', '2025_MAR', '2025_APR', '2025_MAY'],
      dtype='object')

In [21]:
# Count rows with year_month_cols all null or zero
null_or_zero_count = ((df_consumption[year_month_cols].isnull() | (df_consumption[year_month_cols] == 0)).all(axis=1)).sum()
print(f"Number of rows with all null or zero values in year_month_cols: {null_or_zero_count}")

# Drop rows with year_month_cols all null or zero
df_consumption = df_consumption[~(df_consumption[year_month_cols].isnull() | (df_consumption[year_month_cols] == 0)).all(axis=1)]

# Recheck count of rows with year_month_cols all null or zero
null_or_zero_count_after = ((df_consumption[year_month_cols].isnull() | (df_consumption[year_month_cols] == 0)).all(axis=1)).sum()
print(f"Number of rows with all null or zero values in year_month_cols after dropping: {null_or_zero_count_after}")

# Write new dataset to csv
df_consumption.to_csv("../../dataset/clean/training/production/tabular/consumption_consolidated_cleaned.csv", index=False)

Number of rows with all null or zero values in year_month_cols: 298
Number of rows with all null or zero values in year_month_cols after dropping: 0

### Export yearly readings

In [24]:
years = ["2020", "2022", "2023", "2024", "2025"]

# Export yearly readings
for year in years:
    base_cols = ["Control Number", "District", "Street", "Connection Type"]
    
    # Get columns for the current year
    year_cols = [col for col in df_consumption.columns if col.startswith(year)]
    
    # Include 2019_DEC for 2020
    if year == "2020":
        year_cols = ["2019_DEC"] + year_cols

    columns_to_export = base_cols + year_cols

    df_year = df_consumption[columns_to_export]
    df_year.to_csv(f"../../dataset/clean/training/production/yearly/consumption_{year}_cleaned.csv", index=False)
    print(f"Exported {year} data with shape: {df_year.shape}")
    print(f"  Columns: {year_cols}")

Exported 2020 data with shape: (1877, 17)
  Columns: ['2019_DEC', '2020_JAN', '2020_FEB', '2020_MAR', '2020_APR', '2020_MAY', '2020_JUN', '2020_JUL', '2020_AUG', '2020_SEP', '2020_OCT', '2020_NOV', '2020_DEC']
Exported 2022 data with shape: (1877, 16)
  Columns: ['2022_JAN', '2022_FEB', '2022_MAR', '2022_APR', '2022_MAY', '2022_JUN', '2022_JUL', '2022_AUG', '2022_SEP', '2022_OCT', '2022_NOV', '2022_DEC']
Exported 2023 data with shape: (1877, 16)
  Columns: ['2023_JAN', '2023_FEB', '2023_MAR', '2023_APR', '2023_MAY', '2023_JUN', '2023_JUL', '2023_AUG', '2023_SEP', '2023_OCT', '2023_NOV', '2023_DEC']
Exported 2024 data with shape: (1877, 16)
  Columns: ['2024_JAN', '2024_FEB', '2024_MAR', '2024_APR', '2024_MAY', '2024_JUN', '2024_JUL', '2024_AUG', '2024_SEP', '2024_OCT', '2024_NOV', '2024_DEC']
Exported 2025 data with shape: (1877, 9)
  Columns: ['2025_JAN', '2025_FEB', '2025_MAR', '2025_APR', '2025_MAY']